"use client";
/* eslint-disable react-hooks/incompatible-library, @typescript-eslint/no-unused-expressions -- TanStack Table helpers and an intentional URL-state conditional. */
import { useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { flexRender, getCoreRowModel, getFilteredRowModel, getSortedRowModel, type ColumnDef, useReactTable } from "@tanstack/react-table";
import Link from "next/link";
import { ArrowDownUp, ChevronRight, Columns3, Filter, MoreHorizontal, Play, Search, Tag } from "lucide-react";
import { Button, FitScoreBadge, StatusBadge } from "@navo/ui";

export type AccountRow={id:string;name:string;domain:string|null;website:string|null;country:string|null;industry:string|null;employeeRange:string|null;fitScore:number|null;qualification:string;playStatus:string;source:string;ownerName:string|null;lastResearchedAt:Date|null;updatedAt:Date;agentContext:{priority:string;whySelected:string|null;currentStep:string|null;suggestedAction:string|null;targetStatus:string;missionId:string;missionName:string;missionStatus:string}|null};
export function AccountsTable({data}:{data:AccountRow[]}){const router=useRouter();const params=useSearchParams();const [globalFilter,setGlobalFilter]=useState(params.get("q")??"");const [selection,setSelection]=useState({});const columns=useMemo<ColumnDef<AccountRow>[]>(()=>[
  {id:"select",header:({table})=><input type="checkbox" aria-label="选择当前页" checked={table.getIsAllRowsSelected()} onChange={table.getToggleAllRowsSelectedHandler()}/>,cell:({row})=><input type="checkbox" aria-label={`选择 ${row.original.name}`} checked={row.getIsSelected()} onChange={row.getToggleSelectedHandler()}/>,enableSorting:false},
  {accessorKey:"name",header:"Company",cell:({row})=><div className="company-cell"><span className="company-logo">{row.original.name.replace("Demo ","").slice(0,2).toUpperCase()}</span><span className="company-meta"><strong>{row.original.name}</strong><small>{row.original.domain}</small></span></div>},
  {accessorKey:"country",header:"Country"},{accessorKey:"industry",header:"Industry"},
  {accessorKey:"fitScore",header:"Fit Score",cell:({row})=><FitScoreBadge score={row.original.fitScore} status={row.original.qualification}/>},
  {id:"agentPriority",header:"Agent Priority",cell:({row})=><StatusBadge status={row.original.agentContext?.priority??"UNASSIGNED"}/>},
  {id:"mission",header:"Mission · Current Step",cell:({row})=>row.original.agentContext?<div className="company-meta"><Link href={`/app/missions/${row.original.agentContext.missionId}`} onClick={event=>event.stopPropagation()}><strong>{row.original.agentContext.missionName}</strong></Link><small>{row.original.agentContext.currentStep}</small></div>:<span className="muted">Not in a mission</span>},
  {id:"nextAction",header:"Next Best Action",cell:({row})=><span className="agent-next-action">{row.original.agentContext?.suggestedAction??"Review account fit"}<ChevronRight size={12}/></span>},
  {id:"more",header:"",cell:()=><button className="icon-button" aria-label="更多操作"><MoreHorizontal size={15}/></button>,enableSorting:false},
],[]);const table=useReactTable({data,columns,state:{globalFilter,rowSelection:selection},onGlobalFilterChange:setGlobalFilter,onRowSelectionChange:setSelection,getCoreRowModel:getCoreRowModel(),getFilteredRowModel:getFilteredRowModel(),getSortedRowModel:getSortedRowModel(),enableRowSelection:true});const selected=table.getSelectedRowModel().rows.length;return <><div className="toolbar"><div className="toolbar-group"><div className="input-wrap"><Search size={15}/><input className="input input-search" value={globalFilter} onChange={event=>{setGlobalFilter(event.target.value);const next=new URLSearchParams(params);event.target.value?next.set("q",event.target.value):next.delete("q");window.history.replaceState(null,"",`?${next}`)}} placeholder="Search companies or domains…"/></div><button className="button button-secondary" disabled title="Advanced filters are not available in this Alpha."><Filter size={15}/>Filters</button><select className="input" aria-label="Qualification filter"><option>All qualification</option><option>Strong Fit</option><option>Potential Fit</option><option>Review</option></select></div><div className="toolbar-group"><button className="button button-secondary" disabled title="Column customization is not available in this Alpha."><Columns3 size={15}/>Columns</button></div></div>{selected>0&&<div className="alert alert-info" style={{marginBottom:12,justifyContent:"space-between",alignItems:"center"}}><span><strong>{selected}</strong> accounts selected. Navo will keep this exact scope.</span><div className="toolbar-group"><Button variant="secondary" disabled title="Tag editing is not available in this Alpha."><Tag size={14}/>Add tag</Button><Link href="/app/missions/new" className="button button-primary"><Play size={14}/>Create mission</Link></div></div>}<div className="table-shell"><table className="data-table"><thead>{table.getHeaderGroups().map(group=><tr key={group.id}>{group.headers.map(header=><th key={header.id} onClick={header.column.getToggleSortingHandler()} style={{cursor:header.column.getCanSort()?"pointer":"default"}}>{header.isPlaceholder?null:<span style={{display:"inline-flex",alignItems:"center",gap:5}}>{flexRender(header.column.columnDef.header,header.getContext())}{header.column.getCanSort()&&<ArrowDownUp size={11}/>}</span>}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row=><tr key={row.id} onClick={()=>router.push(`/app/accounts/${row.original.id}`)} style={{cursor:"pointer"}}>{row.getVisibleCells().map(cell=><td key={cell.id} onClick={["select","more","mission"].includes(cell.column.id)?event=>event.stopPropagation():undefined}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>)}</tbody></table><div className="table-footer"><span>Showing {table.getRowModel().rows.length} of {data.length} accounts</span><span>25 per page · Page 1</span></div></div></>}
