"use client";
/* eslint-disable react-hooks/incompatible-library, @typescript-eslint/no-unused-expressions -- TanStack Table helpers and an intentional URL-state conditional. */
import { useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { flexRender, getCoreRowModel, getFilteredRowModel, getSortedRowModel, type ColumnDef, useReactTable } from "@tanstack/react-table";
import { ArrowDownUp, Columns3, Download, Filter, MoreHorizontal, Play, Search, Tag } from "lucide-react";
import { Button, FitScoreBadge, StatusBadge } from "@exportplay/ui";

export type AccountRow={id:string;name:string;domain:string|null;website:string|null;country:string|null;industry:string|null;employeeRange:string|null;fitScore:number|null;qualification:string;playStatus:string;source:string;ownerName:string|null;lastResearchedAt:Date|null;updatedAt:Date};
export function AccountsTable({data}:{data:AccountRow[]}){const router=useRouter();const params=useSearchParams();const [globalFilter,setGlobalFilter]=useState(params.get("q")??"");const [selection,setSelection]=useState({});const columns=useMemo<ColumnDef<AccountRow>[]>(()=>[
  {id:"select",header:({table})=><input type="checkbox" aria-label="选择当前页" checked={table.getIsAllRowsSelected()} onChange={table.getToggleAllRowsSelectedHandler()}/>,cell:({row})=><input type="checkbox" aria-label={`选择 ${row.original.name}`} checked={row.getIsSelected()} onChange={row.getToggleSelectedHandler()}/>,enableSorting:false},
  {accessorKey:"name",header:"Company",cell:({row})=><div className="company-cell"><span className="company-logo">{row.original.name.replace("Demo ","").slice(0,2).toUpperCase()}</span><span className="company-meta"><strong>{row.original.name}</strong><small>{row.original.domain}</small></span></div>},
  {accessorKey:"country",header:"Country"},{accessorKey:"industry",header:"Industry"},{accessorKey:"employeeRange",header:"Employees"},
  {accessorKey:"fitScore",header:"Fit Score",cell:({row})=><FitScoreBadge score={row.original.fitScore} status={row.original.qualification}/>},
  {accessorKey:"playStatus",header:"Play Status",cell:({getValue})=><StatusBadge status={String(getValue())}/>},{accessorKey:"ownerName",header:"Owner"},{accessorKey:"source",header:"Source",cell:({getValue})=><span className="badge badge-neutral">{String(getValue()).replaceAll("_"," ")}</span>},
  {accessorKey:"updatedAt",header:"Updated",cell:({getValue})=><span className="muted">{new Date(getValue() as Date).toLocaleDateString("zh-CN")}</span>},
  {id:"more",header:"",cell:()=><button className="icon-button" aria-label="更多操作"><MoreHorizontal size={15}/></button>,enableSorting:false},
],[]);const table=useReactTable({data,columns,state:{globalFilter,rowSelection:selection},onGlobalFilterChange:setGlobalFilter,onRowSelectionChange:setSelection,getCoreRowModel:getCoreRowModel(),getFilteredRowModel:getFilteredRowModel(),getSortedRowModel:getSortedRowModel(),enableRowSelection:true});const selected=table.getSelectedRowModel().rows.length;return <><div className="toolbar"><div className="toolbar-group"><div className="input-wrap"><Search size={15}/><input className="input input-search" value={globalFilter} onChange={event=>{setGlobalFilter(event.target.value);const next=new URLSearchParams(params);event.target.value?next.set("q",event.target.value):next.delete("q");window.history.replaceState(null,"",`?${next}`)}} placeholder="搜索公司或域名…"/></div><button className="button button-secondary"><Filter size={15}/>筛选</button><select className="input" aria-label="Qualification 筛选"><option>全部 Qualification</option><option>Strong Fit</option><option>Potential Fit</option><option>Review</option></select></div><div className="toolbar-group"><button className="button button-secondary"><Columns3 size={15}/>列</button><button className="button button-secondary"><Download size={15}/>导出</button></div></div>{selected>0&&<div className="alert alert-info" style={{marginBottom:12,justifyContent:"space-between",alignItems:"center"}}><span>已选择 <strong>{selected}</strong> 个账户；跨页批量操作不会自动扩大范围。</span><div className="toolbar-group"><Button variant="secondary"><Tag size={14}/>添加标签</Button><Button><Play size={14}/>运行 Play</Button></div></div>}<div className="table-shell"><table className="data-table"><thead>{table.getHeaderGroups().map(group=><tr key={group.id}>{group.headers.map(header=><th key={header.id} onClick={header.column.getToggleSortingHandler()} style={{cursor:header.column.getCanSort()?"pointer":"default"}}>{header.isPlaceholder?null:<span style={{display:"inline-flex",alignItems:"center",gap:5}}>{flexRender(header.column.columnDef.header,header.getContext())}{header.column.getCanSort()&&<ArrowDownUp size={11}/>}</span>}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row=><tr key={row.id} onClick={()=>router.push(`/app/accounts/${row.original.id}`)} style={{cursor:"pointer"}}>{row.getVisibleCells().map(cell=><td key={cell.id} onClick={cell.column.id==="select"||cell.column.id==="more"?event=>event.stopPropagation():undefined}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>)}</tbody></table><div className="table-footer"><span>显示 {table.getRowModel().rows.length} / {data.length} 个账户</span><span>每页 25 · 第 1 页</span></div></div></>}
