"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Command, FilePlus2, Import, ListChecks, Search, Workflow } from "lucide-react";

const actions = [
  { label: "新建 Play", hint: "创建可发布的增长工作流", href: "/app/plays/new", icon: Workflow },
  { label: "导入 Accounts", hint: "上传并映射 CSV", href: "/app/accounts?import=open", icon: Import },
  { label: "新建 Sequence", hint: "设计受控触达时间线", href: "/app/sequences?new=open", icon: FilePlus2 },
  { label: "打开审批队列", hint: "4 条待处理", href: "/app/approvals", icon: ListChecks },
  { label: "搜索 Account / Run", hint: "按名称或 ID 查找", href: "/app/accounts", icon: Search },
];
export function CommandMenu(){const [open,setOpen]=useState(false);const router=useRouter();useEffect(()=>{let g=false;const onKey=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setOpen(value=>!value)}if(event.key.toLowerCase()==="g"){g=true;setTimeout(()=>{g=false},700);return}if(g){const map:Record<string,string>={a:"/app/accounts",p:"/app/plays",r:"/app/runs",v:"/app/approvals"};const path=map[event.key.toLowerCase()];if(path){event.preventDefault();router.push(path);g=false}}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[router]);return <><button className="search-trigger" onClick={()=>setOpen(true)} aria-label="打开全局命令菜单"><Search size={15}/><span>搜索或快速操作</span><span className="keycap">⌘ K</span></button>{open&&<div role="presentation" onMouseDown={()=>setOpen(false)} style={{position:"fixed",inset:0,background:"rgba(15,18,24,.42)",zIndex:100,display:"grid",placeItems:"start center",paddingTop:100}}><section role="dialog" aria-modal="true" aria-label="命令菜单" onMouseDown={event=>event.stopPropagation()} style={{width:"min(620px,calc(100vw - 32px))",background:"#fff",borderRadius:12,border:"1px solid var(--border)",boxShadow:"0 28px 80px rgba(0,0,0,.25)",overflow:"hidden"}}><div style={{height:52,display:"flex",alignItems:"center",gap:10,padding:"0 16px",borderBottom:"1px solid var(--border)"}}><Command size={17}/><input autoFocus placeholder="输入操作、Account 或 Run…" style={{border:0,outline:0,flex:1}} onKeyDown={event=>{if(event.key==="Escape")setOpen(false)}}/></div><div style={{padding:8}}><div className="nav-group">快速操作</div>{actions.map(({label,hint,href,icon:Icon})=><button key={label} onClick={()=>{setOpen(false);router.push(href)}} style={{border:0,background:"transparent",width:"100%",display:"flex",alignItems:"center",gap:11,padding:10,borderRadius:8,textAlign:"left"}}><span className="attention-icon" style={{background:"#f0eeff",color:"var(--accent)"}}><Icon size={16}/></span><span><strong style={{display:"block",fontSize:13}}>{label}</strong><small className="muted">{hint}</small></span></button>)}</div><div style={{borderTop:"1px solid var(--border)",padding:"9px 14px",display:"flex",gap:18,color:"var(--muted)",fontSize:10}}><span>↵ 打开</span><span>Esc 关闭</span><span>G A / G P / G R 快速导航</span></div></section></div>}</>}
