"use client";

import { useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, Rocket, Save, ShieldCheck } from "lucide-react";
import { Badge, Button } from "@navo/ui";
import styles from "@/app/app/missions/missions.module.css";
import { hasResearchWebsite } from "@/lib/mission-command";

type PlayOption={id:string;name:string;description:string|null};
type AccountOption={id:string;name:string;website:string|null;domain:string|null;country:string|null;industry:string|null};
type Preview={provider:string;model:string;plan:{name:string;objective:string;targetDescription:string;steps:Array<{id:string;type:string;title:string;description:string}>;expectedOutputs:string[];assumptions:string[]}};
type FormState={
  name:string;type:string;objective:string;desiredOutcome:string;inputSource:string;targetAccountId:string;
  countries:string;industries:string;playId:string;operatingMode:"OBSERVE"|"RECOMMEND"|"APPROVAL_CONTROLLED";
  approvalPolicy:string;testMode:boolean;maximumAccounts:number;estimatedCostLimit:number;dueAt:string;stopConditions:string;
};
const steps=["Goal","Targets","Playbook","Controls","Limits","Review"];
const missionTypes=[
  ["TARGET_ACCOUNT_DISCOVERY","Target account discovery","Find and qualify accounts matching an ICP."],
  ["EXPANSION_SIGNAL_OUTREACH","Signal-based outreach","Find timely evidence and prepare tailored outreach."],
  ["TRADE_SHOW_LIST_QUALIFICATION","List qualification","Research and rank an imported account list."],
  ["REPLY_FOLLOW_UP","Reply follow-up","Turn recent replies into next actions and tasks."],
] as const;

export function MissionWizard({plays,accounts}:{plays:PlayOption[];accounts:AccountOption[]}){
  const router=useRouter();const params=useSearchParams();
  const initialObjective=params.get("objective")??"";
  const requestedAccountId=params.get("accountId");
  const initialAccountId=accounts.find((account)=>account.id===requestedAccountId&&hasResearchWebsite(account.website))?.id??accounts.find((account)=>hasResearchWebsite(account.website))?.id??"";
  const [step,setStep]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [preview,setPreview]=useState<Preview|null>(null);const [previewing,setPreviewing]=useState(false);
  const [form,setForm]=useState<FormState>({name:"",type:"TARGET_ACCOUNT_DISCOVERY",objective:initialObjective,desiredOutcome:"",inputSource:"DEMO_ACCOUNTS",targetAccountId:initialAccountId,countries:"Germany, Austria, Switzerland",industries:"Packaging, Automotive Components",playId:plays[0]?.id??"",operatingMode:"APPROVAL_CONTROLLED",approvalPolicy:"REQUIRED_FOR_OUTBOUND",testMode:true,maximumAccounts:1,estimatedCostLimit:1,dueAt:"",stopConditions:"Stop on suppression conflict\nNever send without approval"});
  const set=<K extends keyof FormState>(key:K,value:FormState[K])=>setForm((current)=>({...current,[key]:value}));
  const selectedPlay=plays.find((play)=>play.id===form.playId);
  const selectedAccount=accounts.find((account)=>account.id===form.targetAccountId);
  const criteria=useMemo(()=>({countries:split(form.countries),industries:split(form.industries)}),[form.countries,form.industries]);
  const canContinue=step===0?form.name.trim().length>=3&&form.objective.trim().length>=8:step===1?Boolean(selectedAccount&&hasResearchWebsite(selectedAccount.website)):step===4?form.maximumAccounts>0&&form.estimatedCostLimit>=0:true;
  async function loadPreview(){if(!selectedAccount)return;setPreviewing(true);setPreview(null);setError("");try{const response=await fetch("/api/agent/commands/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({command:form.objective})});const payload=await response.json().catch(()=>null) as {data?:Preview;error?:{message?:string}}|null;if(!response.ok||!payload?.data)throw new Error(payload?.error?.message??"AI preview could not be generated.");setPreview(payload.data)}catch(cause){setError(cause instanceof Error?cause.message:"AI preview could not be generated.")}finally{setPreviewing(false)}}
  async function submit(status:"DRAFT"|"ACTIVE"){
    setBusy(true);setError("");
    try{
      if(!selectedAccount||!hasResearchWebsite(selectedAccount.website))throw new Error("Select one workspace account with a valid website before creating a mission.");
      if(!preview)throw new Error("Wait for the AI mission preview before creating a mission.");
      const response=await fetch("/api/missions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.name.trim(),type:form.type,objective:form.objective.trim(),desiredOutcome:form.desiredOutcome.trim()||undefined,status,operatingMode:form.operatingMode,playId:form.playId||undefined,inputSource:form.inputSource,approvalPolicy:form.approvalPolicy,targetAccountId:selectedAccount.id,targetCount:1,maximumAccounts:1,estimatedCostLimit:form.estimatedCostLimit,testMode:form.testMode,dueAt:form.dueAt?new Date(`${form.dueAt}T17:00:00`).toISOString():undefined,targetCriteria:criteria,stopConditions:splitLines(form.stopConditions),plan:preview.plan,provider:preview.provider,model:preview.model}),});
      const payload=await response.json().catch(()=>null) as {missionId?:string;error?:{message?:string}}|null;
      if(!response.ok||!payload?.missionId)throw new Error(payload?.error?.message??"Mission could not be created.");
      router.push(`/app/missions/${payload.missionId}`);router.refresh();
    }catch(caught){setError(caught instanceof Error?caught.message:"Mission could not be created.");setBusy(false)}
  }
  return <div className={styles.wizardShell}>
    <div className={styles.stepper}>{steps.map((label,index)=><div key={label} className={`${styles.step} ${index===step?styles.stepActive:""} ${index<step?styles.stepDone:""}`}><span className={styles.stepCircle}>{index<step?<Check size={14}/>:index+1}</span><span>{label}</span></div>)}</div>
    <div className={styles.wizardGrid}>
      <main className={styles.wizardCard}>
        {step===0&&<><h2>Define the mission goal</h2><p className={styles.wizardIntro}>Give Navo a bounded outcome with enough context to build a controlled plan.</p><div className={styles.field}><label htmlFor="mission-name">Mission name</label><input id="mission-name" value={form.name} onChange={(event)=>set("name",event.target.value)} placeholder="Find high-fit DACH manufacturers" autoFocus/><span className={styles.fieldHint}>A clear, recognizable name for the worklist.</span></div><div className={styles.field}><label htmlFor="mission-objective">Objective</label><textarea id="mission-objective" value={form.objective} onChange={(event)=>set("objective",event.target.value)} placeholder="Identify 20 companies with expansion signals and prepare evidence-backed outreach."/></div><div className={styles.field}><label htmlFor="mission-outcome">Desired outcome</label><input id="mission-outcome" value={form.desiredOutcome} onChange={(event)=>set("desiredOutcome",event.target.value)} placeholder="Five qualified opportunities and approval-ready drafts"/></div><div className={styles.field}><label>Mission type</label><div className={styles.choiceGrid}>{missionTypes.map(([value,title,description])=><label key={value} className={`${styles.choice} ${form.type===value?styles.choiceSelected:""}`}><input type="radio" checked={form.type===value} onChange={()=>set("type",value)}/><strong>{title}</strong><small>{description}</small></label>)}</div></div></>}
        {step===1&&<><h2>Choose one target account</h2><p className={styles.wizardIntro}>This mission safely researches one account and saves a DRAFT only. The selected website is the only research input.</p><div className={styles.field}><label htmlFor="mission-target-account">Account</label><select id="mission-target-account" value={form.targetAccountId} onChange={(event)=>set("targetAccountId",event.target.value)}><option value="">Select a workspace account</option>{accounts.map((account)=><option key={account.id} value={account.id} disabled={!hasResearchWebsite(account.website)}>{account.name}{account.country?` · ${account.country}`:""}{hasResearchWebsite(account.website)?"":" · website required"}</option>)}</select></div>{selectedAccount?<div className="alert alert-info"><ShieldCheck size={16}/><span><strong>{selectedAccount.name}</strong><br/>Website: {hasResearchWebsite(selectedAccount.website)?selectedAccount.website:"No valid website available — this mission cannot start until one is provided."}<br/>{[selectedAccount.industry,selectedAccount.country].filter(Boolean).join(" · ")}</span></div>:<div className="alert alert-warning">Choose an account with a valid website to continue.</div>}<div className={styles.field}><label>Countries</label><input value={form.countries} onChange={(event)=>set("countries",event.target.value)} placeholder="Germany, Austria, Switzerland"/></div><div className={styles.field}><label>Industries</label><input value={form.industries} onChange={(event)=>set("industries",event.target.value)} placeholder="Packaging, Automotive Components"/></div></>}
        {step===2&&<><h2>Select a playbook</h2><p className={styles.wizardIntro}>The playbook defines the repeatable execution path. Navo creates a mission-specific plan from it.</p><div className={styles.choiceGrid}>{plays.map((play)=><label key={play.id} className={`${styles.choice} ${form.playId===play.id?styles.choiceSelected:""}`}><input type="radio" checked={form.playId===play.id} onChange={()=>set("playId",play.id)}/><strong>{play.name}</strong><small>{play.description??"A reusable, controlled workflow."}</small></label>)}</div>{!plays.length&&<div className="alert alert-warning">No playbooks are available. Navo will create a standard deterministic plan.</div>}</>}
        {step===3&&<><h2>Set autonomy and approvals</h2><p className={styles.wizardIntro}>Choose how far Navo may proceed. Policy checks still apply in every mode.</p><div className={styles.choiceGrid}>{([ ["OBSERVE","Observe","Analyze and report without proposing external actions."],["RECOMMEND","Recommend","Prepare next actions for an operator to execute."],["APPROVAL_CONTROLLED","Approval controlled","Execute safe internal work; request approval before outbound actions."] ] as const).map(([value,title,description])=><label key={value} className={`${styles.choice} ${form.operatingMode===value?styles.choiceSelected:""}`}><input type="radio" checked={form.operatingMode===value} onChange={()=>set("operatingMode",value)}/><strong>{title}</strong><small>{description}</small></label>)}</div><div className={styles.field} style={{marginTop:16}}><label>Approval policy</label><select value={form.approvalPolicy} onChange={(event)=>set("approvalPolicy",event.target.value)}><option value="REQUIRED_FOR_OUTBOUND">Required for every outbound action</option><option value="REQUIRED_FOR_HIGH_RISK">Required for high-risk actions</option><option value="RECOMMEND_ONLY">Recommendations only</option></select></div><label className={styles.checkRow}><input type="checkbox" checked={form.testMode} onChange={(event)=>set("testMode",event.target.checked)}/>Use EmailSink test mode. No message can reach a real recipient.</label></>}
        {step===4&&<><h2>Define limits and stop conditions</h2><p className={styles.wizardIntro}>This Batch 2 flow is deliberately limited to one selected account and a saved draft.</p><div className={styles.fieldGrid}><div className={styles.field}><label>Maximum accounts</label><input type="number" value={1} disabled/><span className={styles.fieldHint}>Single-account mission runner.</span></div><div className={styles.field}><label>Estimated cost limit (USD)</label><input type="number" min={0} max={10000} step="0.05" value={form.estimatedCostLimit} onChange={(event)=>set("estimatedCostLimit",Number(event.target.value))}/></div></div><div className={styles.field}><label>Due date</label><input type="date" value={form.dueAt} onChange={(event)=>set("dueAt",event.target.value)}/></div><div className={styles.field}><label>Stop conditions</label><textarea value={form.stopConditions} onChange={(event)=>set("stopConditions",event.target.value)} placeholder="One condition per line"/><span className={styles.fieldHint}>Navo pauses safely when any condition is met.</span></div></>}
        {step===5&&<><h2>Review and create</h2><p className={styles.wizardIntro}>Review the exact schema-validated AI plan that will be saved with this one-account mission.</p><div className={styles.reviewSection}><span>Target</span><strong>{selectedAccount?.name??"No account selected"}</strong><p className="muted" style={{margin:"5px 0 0"}}>Website: {selectedAccount?.website??selectedAccount?.domain??"Missing"}</p></div><div className={styles.reviewSection}><span>Execution</span><strong>{selectedPlay?.name??"Standard mission plan"} · {label(form.operatingMode)}</strong></div><div className={styles.reviewSection}><span>Controls</span><strong>One account · ${form.estimatedCostLimit.toFixed(2)} cost limit · DRAFT only</strong></div>{!preview&&<Button variant="secondary" disabled={previewing} onClick={()=>void loadPreview()}>{previewing?"Generating AI MissionPlan…":"Generate AI MissionPlan preview"}</Button>}{preview&&<section className={styles.reviewSection}><span>AI MissionPlan</span><strong>{preview.provider} · {preview.model}</strong><p className="muted" style={{margin:"6px 0"}}>{preview.plan.targetDescription}</p>{preview.plan.steps.map((item,index)=><div className="list-row" key={item.id}><span><strong>{index+1}. {item.title}</strong><small className="muted" style={{display:"block"}}>{item.description}</small></span><Badge tone="neutral">{label(item.type)}</Badge></div>)}<p className="muted" style={{margin:"9px 0 0"}}>Expected: {preview.plan.expectedOutputs.join(" · ")}</p></section>}<div className="alert alert-info" style={{marginTop:16}}><ShieldCheck size={16}/><span>This mission saves a DRAFT only. It does not send email or create an approval.</span></div></>}
        {error&&<div className={styles.error} role="alert">{error}</div>}
        <footer className={styles.wizardFooter}><Button variant="secondary" disabled={step===0||busy} onClick={()=>setStep((value)=>Math.max(0,value-1))}><ArrowLeft size={14}/>Back</Button>{step<5?<Button disabled={!canContinue} onClick={()=>setStep((value)=>Math.min(5,value+1))}>Continue <ArrowRight size={14}/></Button>:<div style={{display:"flex",gap:8}}><Button variant="secondary" disabled={busy||previewing||!preview} onClick={()=>submit("DRAFT")}><Save size={14}/>Save draft</Button><Button disabled={busy||previewing||!preview} onClick={()=>submit("ACTIVE")}><Rocket size={14}/>{busy?"Creating…":previewing?"Preparing plan…":"Create & start"}</Button></div>}</footer>
      </main>
      <aside className={styles.sidebar}><section className={styles.sideCard}><h3>Mission preview</h3><div className={styles.sideList}><div><span>Type</span><strong>{label(form.type)}</strong></div><div><span>Target</span><strong>{selectedAccount?.name??"Choose account"}</strong></div><div><span>Mode</span><strong>{label(form.operatingMode)}</strong></div><div><span>Budget</span><strong>${form.estimatedCostLimit.toFixed(2)}</strong></div><div><span>Delivery</span><Badge tone="success">DRAFT ONLY</Badge></div></div></section><section className={`${styles.sideCard} ${styles.safety}`}><strong>Safety by default</strong><p style={{margin:"7px 0 0"}}>Navo preserves source evidence, researches only the selected website, and never sends email from this flow.</p></section></aside>
    </div>
  </div>
}
function split(value:string){return value.split(",").map((item)=>item.trim()).filter(Boolean)}
function splitLines(value:string){return value.split("\n").map((item)=>item.trim()).filter(Boolean)}
function label(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,(letter)=>letter.toUpperCase())}
