"use client";

import { useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, Rocket, Save, ShieldCheck } from "lucide-react";
import { Badge, Button } from "@navo/ui";
import styles from "@/app/app/missions/missions.module.css";

type PlayOption={id:string;name:string;description:string|null};
type FormState={
  name:string;type:string;objective:string;desiredOutcome:string;inputSource:string;targetCount:number;
  countries:string;industries:string;playId:string;operatingMode:"OBSERVE"|"RECOMMEND"|"APPROVAL_CONTROLLED";
  approvalPolicy:string;testMode:boolean;maximumAccounts:number;estimatedCostLimit:number;dueAt:string;stopConditions:string;
};
const steps=["Goal","Targets","Playbook","Controls","Limits","Review"];
const missionTypes=[
  ["TARGET_ACCOUNT_DISCOVERY","Target account discovery","Find and qualify accounts matching an ICP."],
  ["EXPANSION_SIGNAL_OUTREACH","Signal-based outreach","Find timely evidence and prepare tailored outreach."],
  ["TRADE_SHOW_LIST_QUALIFICATION","List qualification","Research and rank an imported account list."],
  ["REPLY_FOLLOW_UP","Reply follow-up","Turn recent replies into next actions and tasks."],
] as const;

export function MissionWizard({plays}:{plays:PlayOption[]}){
  const router=useRouter();const params=useSearchParams();
  const initialObjective=params.get("objective")??"";
  const [step,setStep]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const [form,setForm]=useState<FormState>({name:"",type:"TARGET_ACCOUNT_DISCOVERY",objective:initialObjective,desiredOutcome:"",inputSource:"DEMO_ACCOUNTS",targetCount:20,countries:"Germany, Austria, Switzerland",industries:"Packaging, Automotive Components",playId:plays[0]?.id??"",operatingMode:"APPROVAL_CONTROLLED",approvalPolicy:"REQUIRED_FOR_OUTBOUND",testMode:true,maximumAccounts:20,estimatedCostLimit:1,dueAt:"",stopConditions:"Stop on suppression conflict\nNever send without approval"});
  const set=<K extends keyof FormState>(key:K,value:FormState[K])=>setForm((current)=>({...current,[key]:value}));
  const selectedPlay=plays.find((play)=>play.id===form.playId);
  const criteria=useMemo(()=>({countries:split(form.countries),industries:split(form.industries)}),[form.countries,form.industries]);
  const canContinue=step===0?form.name.trim().length>=3&&form.objective.trim().length>=8:step===1?form.targetCount>0:step===4?form.maximumAccounts>0&&form.estimatedCostLimit>=0:true;
  async function submit(status:"DRAFT"|"ACTIVE"){
    setBusy(true);setError("");
    try{
      const response=await fetch("/api/missions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.name.trim(),type:form.type,objective:form.objective.trim(),desiredOutcome:form.desiredOutcome.trim()||undefined,status,operatingMode:form.operatingMode,playId:form.playId||undefined,inputSource:form.inputSource,approvalPolicy:form.approvalPolicy,targetCount:form.targetCount,maximumAccounts:form.maximumAccounts,estimatedCostLimit:form.estimatedCostLimit,testMode:form.testMode,dueAt:form.dueAt?new Date(`${form.dueAt}T17:00:00`).toISOString():undefined,targetCriteria:criteria,stopConditions:splitLines(form.stopConditions)}),});
      const payload=await response.json().catch(()=>null) as {missionId?:string;error?:{message?:string}}|null;
      if(!response.ok||!payload?.missionId)throw new Error(payload?.error?.message??"Mission could not be created.");
      router.push(`/app/missions/${payload.missionId}`);router.refresh();
    }catch(caught){setError(caught instanceof Error?caught.message:"Mission could not be created.");setBusy(false)}
  }
  return <div className={styles.wizardShell}>
    <div className={styles.stepper}>{steps.map((label,index)=><div key={label} className={`${styles.step} ${index===step?styles.stepActive:""} ${index<step?styles.stepDone:""}`}><span className={styles.stepCircle}>{index<step?<Check size={14}/>:index+1}</span><span>{label}</span></div>)}</div>
    <div className={styles.wizardGrid}>
      <main className={styles.wizardCard}>
        {step===0&&<><h2>Define the mission goal</h2><p className={styles.wizardIntro}>Give Navo a bounded outcome with enough context to build a controlled plan.</p><div className={styles.field}><label htmlFor="mission-name">Mission name</label><input id="mission-name" value={form.name} onChange={(event)=>set("name",event.target.value)} placeholder="Find high-fit DACH manufacturers" autoFocus/><span className={styles.fieldHint}>A clear, recognizable name for the worklist.</span></div><div className={styles.field}><label htmlFor="mission-objective">Objective</label><textarea id="mission-objective" value={form.objective} onChange={(event)=>set("objective",event.target.value)} placeholder="Identify 20 companies with expansion signals and prepare evidence-backed outreach."/></div><div className={styles.field}><label htmlFor="mission-outcome">Desired outcome</label><input id="mission-outcome" value={form.desiredOutcome} onChange={(event)=>set("desiredOutcome",event.target.value)} placeholder="Five qualified opportunities and approval-ready drafts"/></div><div className={styles.field}><label>Mission type</label><div className={styles.choiceGrid}>{missionTypes.map(([value,title,description])=><label key={value} className={`${styles.choice} ${form.type===value?styles.choiceSelected:""}`}><input type="radio" checked={form.type===value} onChange={()=>set("type",value)}/><strong>{title}</strong><small>{description}</small></label>)}</div></div></>}
        {step===1&&<><h2>Choose target scope</h2><p className={styles.wizardIntro}>Define where targets come from and the criteria Navo should use to keep the scope precise.</p><div className={styles.fieldGrid}><div className={styles.field}><label>Input source</label><select value={form.inputSource} onChange={(event)=>set("inputSource",event.target.value)}><option value="DEMO_ACCOUNTS">Account database</option><option value="EXISTING_ACCOUNTS">Existing qualified accounts</option><option value="TRADE_SHOW_LIST">Trade show list</option><option value="HISTORICAL_INQUIRIES">Historical inquiries</option><option value="REPLIES">Recent replies</option></select></div><div className={styles.field}><label>Target count</label><input type="number" min={1} max={1000} value={form.targetCount} onChange={(event)=>{const value=Number(event.target.value);set("targetCount",value);if(form.maximumAccounts<value)set("maximumAccounts",value)}}/></div></div><div className={styles.field}><label>Countries</label><input value={form.countries} onChange={(event)=>set("countries",event.target.value)} placeholder="Germany, Austria, Switzerland"/><span className={styles.fieldHint}>Comma-separated. Leave blank to include all countries.</span></div><div className={styles.field}><label>Industries</label><input value={form.industries} onChange={(event)=>set("industries",event.target.value)} placeholder="Packaging, Automotive Components"/></div></>}
        {step===2&&<><h2>Select a playbook</h2><p className={styles.wizardIntro}>The playbook defines the repeatable execution path. Navo creates a mission-specific plan from it.</p><div className={styles.choiceGrid}>{plays.map((play)=><label key={play.id} className={`${styles.choice} ${form.playId===play.id?styles.choiceSelected:""}`}><input type="radio" checked={form.playId===play.id} onChange={()=>set("playId",play.id)}/><strong>{play.name}</strong><small>{play.description??"A reusable, controlled workflow."}</small></label>)}</div>{!plays.length&&<div className="alert alert-warning">No playbooks are available. Navo will create a standard deterministic plan.</div>}</>}
        {step===3&&<><h2>Set autonomy and approvals</h2><p className={styles.wizardIntro}>Choose how far Navo may proceed. Policy checks still apply in every mode.</p><div className={styles.choiceGrid}>{([ ["OBSERVE","Observe","Analyze and report without proposing external actions."],["RECOMMEND","Recommend","Prepare next actions for an operator to execute."],["APPROVAL_CONTROLLED","Approval controlled","Execute safe internal work; request approval before outbound actions."] ] as const).map(([value,title,description])=><label key={value} className={`${styles.choice} ${form.operatingMode===value?styles.choiceSelected:""}`}><input type="radio" checked={form.operatingMode===value} onChange={()=>set("operatingMode",value)}/><strong>{title}</strong><small>{description}</small></label>)}</div><div className={styles.field} style={{marginTop:16}}><label>Approval policy</label><select value={form.approvalPolicy} onChange={(event)=>set("approvalPolicy",event.target.value)}><option value="REQUIRED_FOR_OUTBOUND">Required for every outbound action</option><option value="REQUIRED_FOR_HIGH_RISK">Required for high-risk actions</option><option value="RECOMMEND_ONLY">Recommendations only</option></select></div><label className={styles.checkRow}><input type="checkbox" checked={form.testMode} onChange={(event)=>set("testMode",event.target.checked)}/>Use EmailSink test mode. No message can reach a real recipient.</label></>}
        {step===4&&<><h2>Define limits and stop conditions</h2><p className={styles.wizardIntro}>Bound account volume, spend and timing before Navo begins.</p><div className={styles.fieldGrid}><div className={styles.field}><label>Maximum accounts</label><input type="number" min={1} max={1000} value={form.maximumAccounts} onChange={(event)=>set("maximumAccounts",Number(event.target.value))}/></div><div className={styles.field}><label>Estimated cost limit (USD)</label><input type="number" min={0} max={10000} step="0.05" value={form.estimatedCostLimit} onChange={(event)=>set("estimatedCostLimit",Number(event.target.value))}/></div></div><div className={styles.field}><label>Due date</label><input type="date" value={form.dueAt} onChange={(event)=>set("dueAt",event.target.value)}/></div><div className={styles.field}><label>Stop conditions</label><textarea value={form.stopConditions} onChange={(event)=>set("stopConditions",event.target.value)} placeholder="One condition per line"/><span className={styles.fieldHint}>Navo pauses safely when any condition is met.</span></div></>}
        {step===5&&<><h2>Review and create</h2><p className={styles.wizardIntro}>Save a draft for later review or start the approval-controlled plan now.</p><div className={styles.reviewSection}><span>Goal</span><strong>{form.name}</strong><p className="muted" style={{margin:"5px 0 0",lineHeight:1.5}}>{form.objective}</p></div><div className={styles.reviewSection}><span>Scope</span><strong>{form.targetCount} targets from {label(form.inputSource)} · {criteria.countries.join(", ")||"All countries"}</strong></div><div className={styles.reviewSection}><span>Execution</span><strong>{selectedPlay?.name??"Standard mission plan"} · {label(form.operatingMode)}</strong></div><div className={styles.reviewSection}><span>Controls</span><strong>Maximum {form.maximumAccounts} accounts · ${form.estimatedCostLimit.toFixed(2)} cost limit · {form.testMode?"Test mode on":"Test mode off"}</strong></div><div className="alert alert-info" style={{marginTop:16}}><ShieldCheck size={16}/><span>Outbound activity will stop at a human approval checkpoint under the selected policy.</span></div></>}
        {error&&<div className={styles.error} role="alert">{error}</div>}
        <footer className={styles.wizardFooter}><Button variant="secondary" disabled={step===0||busy} onClick={()=>setStep((value)=>Math.max(0,value-1))}><ArrowLeft size={14}/>Back</Button>{step<5?<Button disabled={!canContinue} onClick={()=>setStep((value)=>Math.min(5,value+1))}>Continue <ArrowRight size={14}/></Button>:<div style={{display:"flex",gap:8}}><Button variant="secondary" disabled={busy} onClick={()=>submit("DRAFT")}><Save size={14}/>Save draft</Button><Button disabled={busy} onClick={()=>submit("ACTIVE")}><Rocket size={14}/>{busy?"Creating…":"Create & start"}</Button></div>}</footer>
      </main>
      <aside className={styles.sidebar}><section className={styles.sideCard}><h3>Mission preview</h3><div className={styles.sideList}><div><span>Type</span><strong>{label(form.type)}</strong></div><div><span>Targets</span><strong>{form.targetCount}</strong></div><div><span>Mode</span><strong>{label(form.operatingMode)}</strong></div><div><span>Budget</span><strong>${form.estimatedCostLimit.toFixed(2)}</strong></div><div><span>Environment</span><Badge tone={form.testMode?"success":"warning"}>{form.testMode?"Test":"Live"}</Badge></div></div></section><section className={`${styles.sideCard} ${styles.safety}`}><strong>Safety by default</strong><p style={{margin:"7px 0 0"}}>Navo preserves source evidence, respects suppressions, stays inside the selected scope, and records every lifecycle action.</p></section></aside>
    </div>
  </div>
}
function split(value:string){return value.split(",").map((item)=>item.trim()).filter(Boolean)}
function splitLines(value:string){return value.split("\n").map((item)=>item.trim()).filter(Boolean)}
function label(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,(letter)=>letter.toUpperCase())}
