import Link from "next/link";
import { Activity, ArrowLeft, CheckCircle2, CircleDollarSign, Clock3, Crosshair, Flag, ShieldCheck, Target, Users } from "lucide-react";
import { notFound } from "next/navigation";
import { DEMO_WORKSPACE_ID, getMission } from "@navo/db/queries";
import { Badge, StatusBadge } from "@navo/ui";
import { MissionActions } from "@/components/mission-actions";
import styles from "../missions.module.css";

const tabs=["summary","targets","plan","activity","outcomes"] as const;
type MissionDetail=NonNullable<Awaited<ReturnType<typeof getMission>>>;
export default async function MissionDetailPage({params,searchParams}:{params:Promise<{missionId:string}>;searchParams:Promise<{tab?:string}>}){
  const [{missionId},{tab="summary"}]=await Promise.all([params,searchParams]);const data=await getMission(DEMO_WORKSPACE_ID,missionId);if(!data)notFound();
  const activeTab=(tabs as readonly string[]).includes(tab)?tab:"summary";
  return <div className="page page-wide"><Link href="/app/missions" className="muted" style={{display:"inline-flex",alignItems:"center",gap:6,marginBottom:12}}><ArrowLeft size={14}/>Back to missions</Link><header className="detail-header"><div className="detail-title"><div className="detail-identity"><span className="detail-logo"><Target size={20}/></span><div><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:5}}><span className={styles.typeLabel}>{label(data.mission.type)}</span><StatusBadge status={data.mission.status}/></div><h1>{data.mission.name}</h1><div className="detail-meta"><span>{label(data.mission.operatingMode)}</span><span>·</span><span>{data.mission.testMode?"Test environment":"Live environment"}</span><span>·</span><span>Updated {formatDate(data.mission.updatedAt)}</span></div></div></div><MissionActions missionId={missionId} status={data.mission.status}/></div><nav className="tabs">{tabs.map((item)=><Link key={item} href={`?tab=${item}`} className={`tab ${activeTab===item?"tab-active":""}`}>{item[0]!.toUpperCase()+item.slice(1)}</Link>)}</nav></header><MissionKpis data={data}/>{activeTab==="targets"?<Targets data={data}/>:activeTab==="plan"?<Plan data={data}/>:activeTab==="activity"?<ActivityView data={data}/>:activeTab==="outcomes"?<Outcomes data={data}/>:<Summary data={data}/>}</div>
}
function MissionKpis({data}:{data:MissionDetail}){const {mission}=data;return <div className={styles.detailKpis}><div className={styles.detailKpi}><span>Progress</span><strong>{mission.progress}%</strong></div><div className={styles.detailKpi}><span>Processed targets</span><strong>{mission.processedCount}/{mission.targetCount}</strong></div><div className={styles.detailKpi}><span>Qualified</span><strong>{mission.qualifiedCount}</strong></div><div className={styles.detailKpi}><span>Needs approval</span><strong>{mission.pendingApprovalCount}</strong></div><div className={styles.detailKpi}><span>Actual cost</span><strong>${Number(mission.actualCost).toFixed(3)}</strong></div></div>}
function Summary({data}:{data:MissionDetail}){const {mission}=data;const criteria=mission.targetCriteria as Record<string,unknown>;const stops=asStrings(mission.stopConditions);return <div className={styles.overviewGrid}><div className="stack"><section className="card"><div className="card-header"><h2>Mission brief</h2><StatusBadge status={mission.status}/></div><p className="summary-text">{mission.objective}</p>{mission.desiredOutcome&&<div className="alert alert-info"><Flag size={16}/><span><strong>Desired outcome</strong><br/>{mission.desiredOutcome}</span></div>}</section><section className="card"><div className="card-header"><h2>Agent summary</h2><Badge tone="accent"><Activity size={12}/>Navo</Badge></div><p className="summary-text">{mission.agentSummary??"Navo has not posted a mission summary yet."}</p><div style={{marginTop:14}}><div style={{display:"flex",justifyContent:"space-between",fontSize:11,marginBottom:7}}><span className="muted">Current progress</span><strong>{mission.progress}%</strong></div><div className={styles.progressTrack}><div className={styles.progressFill} style={{width:`${mission.progress}%`}}/></div><p className="muted" style={{fontSize:11,marginBottom:0}}>{mission.currentStep??"No current step"}</p></div></section></div><aside className="stack"><section className="card"><h2 style={{marginBottom:12}}>Scope & controls</h2><dl className={styles.definitionList}><dt>Input source</dt><dd>{label(mission.inputSource)}</dd><dt>Operating mode</dt><dd>{label(mission.operatingMode)}</dd><dt>Approval policy</dt><dd>{label(mission.approvalPolicy)}</dd><dt>Target criteria</dt><dd>{Object.entries(criteria).map(([key,value])=><div key={key}><strong>{label(key)}:</strong> {Array.isArray(value)?value.join(", "):String(value)}</div>)}</dd><dt>Due date</dt><dd>{mission.dueAt?formatDate(mission.dueAt):"No deadline"}</dd></dl></section><section className="card"><div className="card-header"><h2>Guardrails</h2><ShieldCheck size={16} className="success-text"/></div>{stops.length?stops.map((stop)=><div className="list-row" key={stop}><span>{stop}</span><CheckCircle2 size={14} className="success-text"/></div>):<p className="muted">Default workspace guardrails apply.</p>}</section></aside></div>}
function Targets({data}:{data:MissionDetail}){return <section className="card"><div className="card-header"><div><h2>Target accounts</h2><span className="card-subtitle">{data.targets.length} selected accounts with mission-specific context</span></div><Badge tone="accent"><Users size={12}/>{data.targets.length}</Badge></div>{data.targets.length?<div className="table-shell"><table className="data-table"><thead><tr><th>Account</th><th>Priority</th><th>Status</th><th>Why selected</th><th>Key signal</th><th>Current step</th><th>Confidence</th></tr></thead><tbody>{data.targets.map(({target,account})=><tr key={target.id}><td><Link href={`/app/accounts/${account.id}`} className="company-cell"><span className="company-logo">{account.name.replace("Demo ","").slice(0,2).toUpperCase()}</span><span className="company-meta"><strong>{account.name}</strong><small>{account.country} · {account.industry}</small></span></Link></td><td><StatusBadge status={target.priority}/></td><td><StatusBadge status={target.status}/></td><td style={{whiteSpace:"normal",minWidth:220}}>{target.whySelected??"—"}</td><td style={{whiteSpace:"normal",minWidth:180}}>{target.keySignal??"—"}</td><td>{target.currentStep??"—"}</td><td>{target.findingConfidence?`${Math.round(Number(target.findingConfidence)*100)}%`:"—"}</td></tr>)}</tbody></table></div>:<div className="empty-state"><Crosshair size={24}/><strong>No targets selected</strong><p>This mission does not have target accounts yet.</p></div>}</section>}
function Plan({data}:{data:MissionDetail}){return <div className={styles.overviewGrid}><section className="card"><div className="card-header"><div><h2>{data.plan?.title??"Execution plan"}</h2><span className="card-subtitle">{data.plan?.summary??"Mission-specific deterministic steps"}</span></div>{data.plan&&<StatusBadge status={data.plan.status}/>}</div><div className={styles.planList}>{data.steps.map((step)=><div className={styles.planStep} key={step.id}><span className={styles.planIndex}>{step.order}</span><div><h3>{step.title}</h3><p>{step.description??step.errorMessage??label(step.relatedPlayNodeId??"Mission plan step")}</p>{step.errorMessage&&<div className="alert alert-warning" style={{marginTop:8}}>{step.errorMessage}</div>}</div><StatusBadge status={step.status}/></div>)}</div></section><aside className="stack"><section className="card"><h2 style={{marginBottom:12}}>Plan estimate</h2><dl className={styles.definitionList}><dt>Version</dt><dd>v{data.plan?.version??1}</dd><dt>Duration</dt><dd>{data.plan?.estimatedDurationMinutes??"—"} minutes</dd><dt>Estimated cost</dt><dd>${Number(data.plan?.estimatedCost??0).toFixed(3)}</dd><dt>Steps</dt><dd>{data.steps.length}</dd></dl></section></aside></div>}
function ActivityView({data}:{data:MissionDetail}){return <section className="card"><div className="card-header"><div><h2>Mission activity</h2><span className="card-subtitle">A durable timeline of agent work and operator decisions</span></div><Badge tone="neutral"><Activity size={12}/>{data.events.length}</Badge></div><div className={styles.eventList}>{data.events.map((event)=><article className={styles.event} key={event.id}><span className={styles.eventDot} style={{background:event.severity==="ERROR"?"var(--danger)":event.severity==="WARNING"?"var(--warning)":event.severity==="SUCCESS"?"var(--success)":"var(--accent)"}}/><div><h3>{event.title}</h3><p>{event.description??label(event.type)}</p></div><time>{formatDateTime(event.occurredAt)}</time></article>)}</div></section>}
function Outcomes({data}:{data:MissionDetail}){const {mission}=data;const completed=data.steps.filter((step)=>step.status==="COMPLETED").length;const successRate=mission.processedCount?Math.round(mission.qualifiedCount/mission.processedCount*100):0;return <div className={styles.overviewGrid}><div className="stack"><section className="card"><div className="card-header"><h2>Outcome summary</h2><StatusBadge status={mission.status}/></div><p className="summary-text">{mission.agentSummary??mission.desiredOutcome??"Outcome data will appear as Navo processes the mission."}</p><div className={styles.metricRow}><span className={styles.miniMetric}><span>Qualification rate</span><strong>{successRate}%</strong></span><span className={styles.miniMetric}><span>Plan steps done</span><strong>{completed}/{data.steps.length}</strong></span><span className={styles.miniMetric}><span>Approval queue</span><strong>{mission.pendingApprovalCount}</strong></span><span className={styles.miniMetric}><span>Cost / target</span><strong>${mission.processedCount?(Number(mission.actualCost)/mission.processedCount).toFixed(3):"0.000"}</strong></span></div></section><section className="card"><div className="card-header"><h2>Desired vs. actual</h2><Flag size={16} className="muted"/></div><dl className={styles.definitionList}><dt>Desired outcome</dt><dd>{mission.desiredOutcome??"No desired outcome specified"}</dd><dt>Processed</dt><dd>{mission.processedCount} of {mission.targetCount} targets</dd><dt>Qualified</dt><dd>{mission.qualifiedCount} accounts</dd><dt>Completion</dt><dd>{mission.completedAt?formatDateTime(mission.completedAt):"Mission is still open"}</dd></dl></section></div><aside className="stack"><section className="card"><div className="card-header"><h2>Resource use</h2><CircleDollarSign size={16} className="success-text"/></div><dl className={styles.definitionList}><dt>Actual cost</dt><dd>${Number(mission.actualCost).toFixed(5)}</dd><dt>Cost limit</dt><dd>{mission.estimatedCostLimit?`$${Number(mission.estimatedCostLimit).toFixed(2)}`:"No limit"}</dd><dt>Maximum accounts</dt><dd>{mission.maximumAccounts??mission.targetCount}</dd><dt>Test mode</dt><dd>{mission.testMode?"Enabled":"Disabled"}</dd></dl></section><section className="card"><div className="card-header"><h2>Timing</h2><Clock3 size={16} className="muted"/></div><dl className={styles.definitionList}><dt>Started</dt><dd>{mission.startedAt?formatDateTime(mission.startedAt):"Not started"}</dd><dt>Due</dt><dd>{mission.dueAt?formatDateTime(mission.dueAt):"No deadline"}</dd><dt>Completed</dt><dd>{mission.completedAt?formatDateTime(mission.completedAt):"—"}</dd></dl></section></aside></div>}
function label(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,(letter)=>letter.toUpperCase())}
function formatDate(value:Date){return new Intl.DateTimeFormat("en",{year:"numeric",month:"short",day:"numeric"}).format(value)}
function formatDateTime(value:Date){return new Intl.DateTimeFormat("en",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(value)}
function asStrings(value:unknown){return Array.isArray(value)?value.filter((item):item is string=>typeof item==="string"):[]}
